### ISSUE TITLE
Send email form data

### ISSUE THREAD

**Issue by chathurangaSachindra** [pepipost/docs#2]
Need to get an idea to send an email with form data.

**Comment by ParthKetanDoshi** [comment]
Is the issue open for contribution ?

**Comment by geniusdibya** [comment]
@ParthKetanDoshi this one is closed. You will find the opened issue for contribution here: https://github.com/search?q=org%3Apepipost+label%3Ahacktoberfest+type%3AIssues&type=Issues&utf8=%E2%9C%93
